name: Comment to label

on:
  issues:
    types: [labeled]
  workflow_call:

jobs:
  issueLabeled:
    runs-on: ubuntu-latest
    steps:
      - name: Bounty explanation
        uses: peter-evans/create-or-update-comment@v2
        if: github.event.label.name == '💰bounty'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: >
            There is a bounty on this issue. The amount is in the title. The reward will be awarded to the first person or group of people who resolve this issue.


            If you are starting to work on this bounty, please write a comment so that we can assign the issue to you. We expect contributors to provide a PR in a reasonable timeframe or, in case of an extensive work, updates on their progress. We will unassign the issue if we feel the assignee is not responsive or has abandoned the task.


            Read the [full conditions and details](https://github.com/woodser/monero-cpp/blob/master/docs/bounties.md) of the bounty system.
